server:
  port: 8091
spring:
  application:
    name: ms-shopping-cart
  datasource:
    url: jdbc:postgresql://localhost:5432/db_cart
    username: user_vrakben
    password: password_vrakben
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/