spring.application.name=catalog

# Redis Cache Configuration
spring.data.redis.host=${SPRING_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_REDIS_PORT:6379}
spring.cache.type=redis
spring.cache.redis.time-to-live=300000
