server:
  port: 8084
spring:
  application:
    name: catalog
  datasource:
    url: jdbc:postgresql://vrakben-db:5432/vrakben_db
    username: user_vrakben
    password: password_vrakben
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/