server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        # Ruta para el Stock Engine
        - id: stock-engine-route
          uri: lb://ms-stock-engine
          predicates:
            - Path=/api/stock/**

        # Ruta para el Agendamiento
        - id: appointment-route
          uri: lb://ms-appointment-scheduler
          predicates:
            - Path=/api/appointments/**

        # Ruta para el Historial
        - id: vehicle-history-route
          uri: lb://ms-vehicle-history
          predicates:
            - Path=/api/history/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/