server:
  port: 8080

spring:
  application:
    name: bff
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        # Ruta para el Auth Server (Pública, sin filtro JWT)
        - id: auth-server-route
          uri: http://auth-server:8083
          predicates:
            - Path=/api/auth/**

        # Ruta para el Catálogo (Se requiere token, a menos que el GET sea público, por ahora proteger todo)
        - id: catalog-route
          uri: http://ms-catalog:8084
          predicates:
            - Path=/api/catalog/**
          filters:
            - JwtAuthentication

        # Ruta para el Stock Engine (Protegida)
        - id: stock-engine-route
          uri: http://ms-stock-engine:8080
          predicates:
            - Path=/api/stock/**
          filters:
            - JwtAuthentication

        # Ruta para el Agendamiento (Protegida)
        - id: appointment-route
          uri: http://ms-appointment-scheduler:8080
          predicates:
            - Path=/api/appointments/**
          filters:
            - JwtAuthentication

        # Ruta para el Historial (Protegida)
        - id: vehicle-history-route
          uri: http://ms-vehicle-history:8080
          predicates:
            - Path=/api/history/**
          filters:
            - JwtAuthentication

        # Ruta para el Carrito (Protegida)
        - id: shopping-cart-route
          uri: http://ms-shopping-cart:8091
          predicates:
            - Path=/api/cart/**
          filters:
            - JwtAuthentication

        # Ruta para Órdenes y Checkout (Protegida)
        - id: order-management-route
          uri: http://ms-order-management:8080
          predicates:
            - Path=/api/orders/**
          filters:
            - JwtAuthentication

        # Ruta para Órdenes de Trabajo de Mecánicos (Protegida)
        - id: job-orders-route
          uri: http://ms-job-orders:8080
          predicates:
            - Path=/api/jobs/**
          filters:
            - JwtAuthentication

        # Ruta para Solicitud de Materiales (Protegida)
        - id: supplier-procurement-route
          uri: http://ms-supplier-procurement:8080
          predicates:
            - Path=/api/procurement/**
          filters:
            - JwtAuthentication

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.cloud.gateway: TRACE
