server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: file:///C:/Users/tu-usuario/Documents/configs
  profiles:
    active: native

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/